### ISSUE TITLE
CANNOT BUILD AGAIN DX

### ISSUE THREAD

**Issue by GittyWidders** [XAYRGA/ibnktool#1]
BUILDING THIS PROGRAM ON VISUAL STUDIO ON MY COMPUTER IS IMPOSSIBLE AND I GIVE A ----!
THAT BUILDING ERROR OVERFLOW IS DRIVING ME ----ING ANGEARLY! GOD----IT XAYRGA!
YOU LITTLE PIECE OF ----! SEND ME THE GOD---- RELEASE OR I WILL REMOVE YOUR ACCOUNT!

Sorry for the stupid words I am typing, but try sending me a release before I go nuts.

**Comment by XAYRGA** [comment]
what the hell lmao

http://www.xayr.ga/tools/SoundModdingToolkit/
