### ISSUE TITLE
Can't deserialize Twilight Princess IBNK files

### ISSUE THREAD

**Issue by Github3010** [XAYRGA/ibnktool#4]
I keep getting NullReferenceException every time I deserialize the three BGM banks in TP. Here is the files:
https://drive.google.com/file/d/11uDgPLHaQz4tjAvX2e-pb3SHNS212wNA/view?usp=sharing

Look at them in a hex editor to see if there is something wrong with them.

**Comment by Github3010** [comment]
Need to give you a hint that it outputs "Object reference not set to an instance of an object."

**Comment by XAYRGA** [comment]
ibnktool's support for BNKV2 is lacking significantly -- I've been meaning to address it but haven't yet, it will probably come with the rewrite of all of the other tools.

**Comment by Github3010** [comment]
So when will the "ibnktool's support for BNKV2 is lacking significantly -- I've been meaning to address it but haven't yet, it will probably come with the rewrite of all of the other tools" issue be fixed?

**Comment by XAYRGA** [comment]
wontfix
